# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2.11-fpm
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:5.7

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "sf-project/composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd sf-project && composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "sf-project/composer.json" }}
        
      # run tests!
      - run: cd sf-project && ls -lah && pwd && ls -lah bin
      - run: cd sf-project && bin/phpunit